apiVersion: apps/v1
kind: Deployment
metadata:
  name: where-was-it-client-deployment
  labels:
    app: js
    tier: frontend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: js
  template:
    metadata:
      labels:
        app: js
    spec:
      containers:
        - name: where-was-it-client
          # leave this for kustomize
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          ports:
            - containerPort: 80
