apiVersion: apps/v1
kind: Deployment
metadata:
  name: where-was-it-backend-deployment
  labels:
    app: python
    tier: backend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
        - name: where-was-it-backend
          # leave this for kustomize
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          ports:
            - containerPort: 5000
